### ISSUE TITLE
Kernel Panic on Shutdown

### ISSUE THREAD

**Issue by ghost** [afzalarsalan/linux-surfacebook#1]
On shutdown or reboot, system crashes with kernel panic.

**Comment by afzalarsalan** [comment]
For one I guess I'm surprised you even found this because I haven't really uploaded this anywhere. Also I would appreciate if you could get me more details like maybe a picture of the panic and which branch you are using in particular. Keep in Mind that Master is where I kind of keep the "production" version of this. Also I added the IPTS driver to this and have not yet added to the wiki that you need to complete the steps listed [here](https://github.com/ipts-linux-org/ipts-linux-new/wiki) under the Firmware section. It's actual some what likely this might be your issue since I built ipts into the kernel instead of as a module.

**Comment by ghost** [comment]
Haha, it's one of the only ones that actually compiled with no hitches. I'm using the master branch.

So I've followed those instructions and I no longer get the kernel panic on shutdown. I still have no working touch, however.

**Comment by afzalarsalan** [comment]
I probably should have been a little more specific since those instructions don't really apply globally at least in our case. If you are running the Surface Book and not the Surface Pro 4, you actually want to use the SurfaceTouchServicing..0076.bin for all three of the files. Don't know why in particular but this one works best on the Surface Book, the aformentioned 0078 seems to work best on the Surface Pro 4 and for some reason the new 0079 causes inverted y axis touch on both, go figure. Also if you are using Arch Linux as I presume you are, the i915 GuC firmware on that page already comes with the linux-firmware package which is installed as part of base on pretty much all systems. Just mentioning that for future reference if other people read this.

**Comment by afzalarsalan** [comment]
Any luck?

**Comment by ghost** [comment]
I ended up reinstalling arch and trying from scratch. This time, it worked. (Quite well, I may add)

I'd rather not barrage this repo with issues but have you had any luck with suspend/hibernate?
