### ISSUE TITLE
No Graphics with this Kernel

### ISSUE THREAD

**Issue by itsyoshio** [afzalarsalan/linux-surfacebook#3]
It's probably my fault but any idea whats happening?

When trying to boot into this Kernel, i'm left with a Blank Screen and a _ Cursor right after 
"Reached Target Graphical Interface"

Booting with nomodeset results in the same.
When Disabling my desktop manager i can use the shell perfectly fine.
I tried GDM and SDDM, reinstalled x86-intel and mesa.

I have a Surface Book with i5 and dgpu, but that probably shouldn't matter since lscpi -v only finds the Intel HD 520

**Comment by afzalarsalan** [comment]
This most likely sounds like an issue with your xorg or wayland setup primarily due to the fact you even reach the graphic interface means that KMS has already initiated and the kernel driver is probably not the cause of your regression. Also I'm betting you're using master because every other branch is mostly broken into a million peices. I know that the latest kernel is working at least for my case because I use it on a day to day basis. Try looking at your journalctl and see if you can see an error popping up upon starting up your display manager.

**Comment by itsyoshio** [comment]
I reinstalled Arch and its working. Sorry for the Trouble.
