### ISSUE TITLE
I don't know where to ask (about powertop)

### ISSUE THREAD

**Issue by alkeryn** [afzalarsalan/linux-surfacebook#5]
So you recomanded to use powertop but what are you recomanded settings for it ? =)

**Comment by afzalarsalan** [comment]
Sorry for the delay, college consumes time. As for powertop, I just use powertop --auto-tune on boot which I found an example for [here](https://wiki.archlinux.org/index.php/powertop). Also checkout [tlp](https://wiki.archlinux.org/index.php/TLP) as that's something that's been beneficial for me as well. I'm going to close this because this isn't a trend I want to start for github issues but a great place to ask question is the [/r/SurfaceLinux](https://www.reddit.com/r/SurfaceLinux/) subreddit which I monitor on regular occasion. Usually other people suffer from the same problems as this is something that's pretty generic to Linux on the Surface Book/Pro in general. If there's something that pertains directly to this kernel, definately open an issue though because I use this as a bug tracker for whenever I have free time.

**Comment by afzalarsalan** [comment]
I realize that apparently a lot of questions have come up on the subreddit already. Sorry, again was busy with school and didn't get to really check it.
